#!/bin/bash
# Copyright (C) 2017 Luis R. Rodriguez <mcgrof@kernel.org>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of copyleft-next (version 0.3.1 or later) as published
# at http://copyleft-next.org/.

function setup_headers()
{
	if [ -z $KVM_BOOT_LIB_DIR ]; then
		KVM_BOOT_LIB_DIR=$(dirname $0)
	fi
	source $KVM_BOOT_LIB_DIR/lib.sh
}

function set_kvm_boot_install()
{
	if [ -z $KVM_BOOT ]; then
		KVM_BOOT=(
			$KVM_BOOT_QEMU
			-cpu kvm64
			-enable-kvm
			#-kernel $kernel
			-m 1024
			-smp 1
			-netdev vde,sock=$KVM_BOOT_VDE_SOCKET,group=kvm,mode=0660,id=vde0
			-device e1000,netdev=vde0,mac=52:54:00:12:34:84
			-no-reboot
			-cdrom $KVM_BOOT_ISO
			-watchdog i6300esb
			-rtc base=localtime
			-hda $KVM_BOOT_TARGET
			$KVM_BOOT_USE_NEXT_TARGETT
			-boot order=d
		)
	fi
}


function usage()
{
	echo -e "Usage $0 [ -i path-to-some-iso | -t path-to-some-img ]"
	echo -e ""
	echo -e "-i -- Use the specified file as the KVM_BOOT_ISO we will boot from"
	echo -e "-t -- Use the specified file as the disk image target"
	echo -e "-n -- Use the specified file as the linux-next disk image target"
	echo -e "-l -- List available KVM_BOOT_ISO files"
	echo -e "-d -- Use development version of qemu"
	echo -e ""
	echo -e "For example valid uses:"
	echo -e "\t$0 -i $KVM_BOOT_ISO -t $KVM_BOOT_TARGET"
	echo -e "\t$0 -l"
	echo -e ""
}

function parse_args()
{
	case $1 in
		"--help")
			usage
			exit 1
			;;
		"-h")
			usage
			exit 1
			;;
		"-d")
			shift
			KVM_BOOT_QEMU="$HOME/devel/qemu/x86_64-softmmu/qemu-system-x86_64"
			parse_args $@
			;;
		"-i")
			shift
			KVM_BOOT_ISO=$1
			shift
			parse_args $@
			;;
		"-t")
			shift
			KVM_BOOT_TARGET=$1
			shift
			parse_args $@
			;;
		"-n")
			shift
			KVM_BOOT_NEXT_TARGET=$1
			if [[ "$KVM_BOOT_NEXT_TARGET" == "none" ]]; then
				KVM_BOOT_USE_NEXT_TARGET=""
			else
				KVM_BOOT_USE_NEXT_TARGET="-hdb $KVM_BOOT_NEXT_TARGET"
			fi
			shift
			parse_args $@
			;;
		"-l")
			ls -R $KVM_BOOT_ISO_PATH
			exit
			;;
		*)
			;;
	esac
}

setup_headers
allow_user_defaults
parse_args $@

set_kvm_boot_install

"${KVM_BOOT[@]}"
